// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension="
// @generated from file codestash.proto (package codestash, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetRepoRecordsRequest, GetRepoRecordsResponse } from "./codestash_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service codestash.Service
 */
export const Service = {
  typeName: "codestash.Service",
  methods: {
    /**
     * @generated from rpc codestash.Service.GetRepoRecords
     */
    getRepoRecords: {
      name: "GetRepoRecords",
      I: GetRepoRecordsRequest,
      O: GetRepoRecordsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

